#!/usr/bin/env python3
"""
간단한 favicon.ico 생성 스크립트
"""

import base64
import struct

# ICO 파일 헤더 (32x32, 16 colors)
# 간단한 16색 32x32 ICO 파일 생성
ico_data = base64.b64decode(
    'AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
)

# 더 간단한 방법: SVG를 ICO처럼 사용하거나, 빈 ICO 파일 생성
# 대신 간단한 16x16 ICO를 직접 생성
ico_header = struct.pack('<HHH', 0, 1, 1)  # Reserved, Type (1=ICO), Count
ico_entry = struct.pack('<BBBBHHII', 32, 32, 0, 0, 1, 32, 22, 0)  # Width, Height, Colors, Reserved, Planes, BitCount, Size, Offset

# 32x32 픽셀 데이터 (간단한 검은 배경에 흰색 S)
# 32x32 = 1024 픽셀, 1비트 = 128 bytes per plane, 4 planes = 512 bytes
# 간단하게 모두 검은색으로
pixel_data = b'\x00' * 512

ico_file = ico_header + ico_entry + pixel_data

with open('favicon.ico', 'wb') as f:
    f.write(ico_file)

print("favicon.ico 파일이 생성되었습니다.")

